### ISSUE TITLE
Some suggestions to improve readability

### ISSUE THREAD

**Issue by fedecalendino** [xilopaint/alfred-urban-dictionary#10]
Hi!

I quite like this workflow, it's super handy!

I have a few suggestions that might improve the readability of the results.

1. Switch the titles and the subtitles to give more importance to the definitions rather than their scoring.

2. Remove all the `[...]` that are associated with links to other UD pages.

3. Sort the results by their 👍🏻 score (or maybe by the ratio of 👎🏻 / 👍🏻)

4. Remove the word you are looking for from the subtitle.

BEFORE:

<img width="764" alt="before" src="https://github.com/xilopaint/alfred-urban-dictionary/assets/7383708/cb6d502a-c39e-433b-bf9a-ab84b73e7a6d">

AFTER:

<img width="764" alt="after" src="https://github.com/xilopaint/alfred-urban-dictionary/assets/7383708/0bfb3c42-7603-443e-935d-4b0df46878df">

Cheers,
Fede.

**Comment by fedecalendino** [comment]
ps: i'd happily push a PR for this repo if you want.

**Comment by xilopaint** [comment]
Results are sorted the same way as the website what means the workflow follows UD's own algorithm. A higher like count doesn't mean a higher score and therefore a more relevant result as you also have dislikes, that's why I'm not willing to change this part. As for switching titles and subtitles and omitting the search term, it's problematic for more than one reason. Firstly, your approach implies that the resulting words are always identical to what you typed and it's not true. See:

<img width="764" alt="Screenshot 2023-06-04 at 09 51 47" src="https://github.com/xilopaint/alfred-urban-dictionary/assets/11052366/6b3d2b96-73c3-4f13-a3a5-30ad7e5e5461">

Also, the large title font allows less content to be displayed. 

Regarding, `[...]` I agree with the suggestion and would accept a PR to fix this.

**Comment by fedecalendino** [comment]
Right, I wasn't aware of that!

I'll make the PR for the brackets.


Cheers.

**Comment by xilopaint** [comment]
Good.

**Comment by fedecalendino** [comment]
https://github.com/xilopaint/alfred-urban-dictionary/pull/11
